### ISSUE TITLE
What is the correct context URL for CodeMeta? 

### ISSUE THREAD

**Issue by ddeboer** [CLARIAH/tool-discovery#20]
While validating a `codemeta.json` file against our SHACL shapes graph (#2), I stumbled upon the problem of how to define CodeMeta’s JSON-LD context. Should it be:

- http://schema.org, as documented on https://codemeta.github.io/user-guide/ 
- or https://doi.org/10.5063/SCHEMA/CODEMETA-2.0, as documented on that same page, which redirects to https://raw.githubusercontent.com/codemeta/codemeta/2.0/codemeta.jsonld?
- or https://codemeta.github.io/terms/, which we find in https://doi.org/10.5063/SCHEMA/CODEMETA-2.0?

**Comment by proycon** [comment]
The JSON-LD file at https://raw.githubusercontent.com/codemeta/codemeta/2.0/codemeta.jsonld (which the DOI URL links too as well) defines:

```
"@context": {
      "schema":"http://schema.org/",
      "codemeta": "https://codemeta.github.io/terms/",
}
```

So that's what I'm using. Terms that have already been incorporated in schema.org use the schema namespace, only the ones that are not merged upstream yet use the codemeta namespace. The JSON-LD file specifically maps all used properties to one of these namespaces.

In [codemetapy](https://github.com/proycon/codemetapy) I did implement some logic to 'correct' namespaces that slightly diverge (e.g. https instead of http). See https://github.com/proycon/codemetapy/blob/master/codemeta/common.py#L23 for the exact namespaces I use.
