### ISSUE TITLE
Is it possible to do a live validation of the metadata.json file?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/tool-discovery#32]
Hi, when running:

`docker run -v $(pwd):/data proycon/codemeta-harvester --stdout --validate /data/schemas/shacl/software.ttl /data/source-registry/burgerLinker.yml`
 
or

`docker run -v $(pwd):/data proycon/codemeta-harvester --stdout --validate /data/schemas/shacl/software.ttl /data/source-registry/cow.yml`

I no longer expected the following message in the review/reviewBody:

`Info: The funder *SHOULD* be acknowledged (This is missing in the metadata)\n
`
Since for both cow and burgerLinker these are provided.  Therefore I assume, the` --validate` option, does actually not validate the *current* metadata. I think I read that updates are done daily, but that would not hold for cow, which has the funder info for a week now. A 'live' validation would help to directly check whether all required info is provided.

**Comment by proycon** [comment]
> Therefore I assume, the --validate option, does actually not validate the current metadata.

Correct. The way you invoked it is very close to how the harvester on the server runs. That means it will fetch the software from github itself, check out *the latest stable* release (= git tag with some semantic version content) and run the validation. If you haven't done any releases since the metadata changes and they live only in the master branch, they won't show on the official server. This is documented here btw: https://github.com/CLARIAH/tool-discovery/blob/master/CONTRIBUTING.md#q-why-cant-i-see-my-metadata-changes-reflected

>  A 'live' validation would help to directly check whether all required info is provided.

I agree. You want to check prior to releasing, even before committing and pushing. I should probably document this a bit better or make it easier. You can currently do so as follows:

Run from the root directory of your project (not this repo):

```
$ docker run -v $(pwd):/data -v /path/to/tool-discovery:/tool-discovery proycon/codemeta-harvester --stdout --validate /tool-discovery/schemas/shacl/software.ttl
```

Make sure `/path/to/tool-discovery' point to wherever you checkout out this tool-discovery repo.

**Comment by proycon** [comment]
I tried to document this a bit better now in commit https://github.com/CLARIAH/tool-discovery/commit/a006aad32f51a483871bcaf51566f3716f98ab9a

**Comment by rlzijdeman** [comment]
Thank you so much. I now understand the difference between the processes and was able to successfully apply method 2.
