### ISSUE TITLE
README not found

### ISSUE THREAD

**Issue by pebbe** [CLARIAH/tool-discovery#37]
At https://tools.clariah.nl/alud/ I get:

    Violation: Software source code *MUST* have a proper README. (This is missing in the metadata)

There is a `README.md` in the repository. Why is it ignored? I don't see how to point to it in `codemeta.json`

**Comment by proycon** [comment]
Good point, it seems this is missing in the sofware metadata requirement. The readme URL can be specified via the "readme"  field (`codemeta:readme`) in `codemeta.json` .

Currently the harvester doesn't look any further because it sees your `codemeta.json` and assumes it's fairly complete (only a few things are still harvested then),  but I think I can improve that behaviour and add the README if it it's missing, that'd make more sense and would solve your case automatically.

**Comment by proycon** [comment]
This has been implemented now.
